### Inspect Bruker stack

In [1]:
import tifffile

path = r"\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\836174\836174_2026-06-17_12-51-17\reference_volume\2026-06-17_836174_stack_00001.tif"

with tifffile.TiffFile(path) as tif:
    print(len(tif.pages))
    print(tif.pages[0].shape)
    print(tif.pages[0].dtype)
    print(tif.pages[0].description[:4000])

3540
(2048, 2048)
int16
frameNumbers = 1
acquisitionNumbers = 1
frameNumberAcquisition = 1
frameTimestamps_sec = 0.000000000
acqTriggerTimestamps_sec = -0.000106335
nextFileMarkerTimestamps_sec = -1.000000000
endOfAcquisition = 0
endOfAcquisitionMode = 0
dcOverVoltage = 0
epoch = [2026  6 18 14 48 46.513]
auxTrigger0 = []
auxTrigger1 = []
auxTrigger2 = []
auxTrigger3 = []
I2CData = {}


### Inspect SLAP2 volume

In [2]:
from pathlib import Path
import tifffile

paths = [
    r"\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\836174\836174_2026-06-17_12-51-17\slap2\static_data\structure_volume_20260617_132712_DMD1-REFERENCE.tif",
    r"\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\836174\836174_2026-06-17_12-51-17\slap2\static_data\structure_volume_20260617_132712_DMD2-REFERENCE.tif",
]

for p in paths:
    p = Path(p)
    print("\n==", p.name)
    with tifffile.TiffFile(p) as tif:
        print("n pages:", len(tif.pages))
        print("series count:", len(tif.series))
        for i, s in enumerate(tif.series):
            print("series", i, "shape:", s.shape, "axes:", s.axes, "dtype:", s.dtype)

        for idx in [0, 1, 2, len(tif.pages)//2, len(tif.pages)-1]:
            page = tif.pages[idx]
            print("\nPAGE", idx)
            print("shape:", page.shape, "dtype:", page.dtype)
            desc = page.description or ""
            print(desc[:3000])


== structure_volume_20260617_132712_DMD1-REFERENCE.tif
n pages: 101
series count: 1
series 0 shape: (101, 800, 1280) axes: IYX dtype: float32

PAGE 0
shape: (800, 1280) dtype: float32
{"SLAP2ReferenceStackFileVersion":2,"z":-199.875,"channel":1,"acquisitionPathIdx":1,"sourceTifFile":"F:\\slap2Data\\836174_2026-06-17_12-51-17\\ref_volume_20260617_132712_DMD1.tif","dmdPixel2SampleTransform":[[0.24907835903790651,-0.0008847190020129167,0,-1.902316580004602],[0.0029171477472943433,0.25063596511811065,0,-0.63452150251753014],[0,0,1,-199.875],[0,0,0,1]]}

PAGE 1
shape: (800, 1280) dtype: float32
{"SLAP2ReferenceStackFileVersion":2,"z":-198.375,"channel":1,"acquisitionPathIdx":1,"sourceTifFile":"F:\\slap2Data\\836174_2026-06-17_12-51-17\\ref_volume_20260617_132712_DMD1.tif","dmdPixel2SampleTransform":[[0.24907835903790651,-0.0008847190020129167,0,-1.902316580004602],[0.0029171477472943433,0.25063596511811065,0,-0.63452150251753014],[0,0,1,-199.875],[0,0,0,1]]}

PAGE 2
shape: (800, 1280) dtyp

In [4]:
import h5py
import numpy as np

meta = [
    r"\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\836174\836174_2026-06-17_12-51-17\slap2\static_data\structure_volume_20260617_132712_DMD1.meta",
    r"\\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\836174\836174_2026-06-17_12-51-17\slap2\static_data\structure_volume_20260617_132712_DMD2.meta"
]

for p in meta:
    print("\n==", p)
    with h5py.File(p, "r") as f:
        for key in [
            "acquisitionPathIdx",
            "acquisitionPathName",
            "channelsSave",
            "dmdPixelsPerColumn",
            "dmdPixelsPerRow",
            "remoteFocusPosition_um",
            "AcquisitionContainer/ScannerParameters/fovSize",
            "AcquisitionContainer/ScannerParameters/pixelDilationXY",
            "AcquisitionContainer/ParsePlan/rasterOffsetXY",
            "AcquisitionContainer/ParsePlan/rasterSizeXY",
            "#refs#/P1/dmdPixel2SampleTransform",
            "#refs#/Q1/dmdPixel2SampleTransform",
        ]:
            if key in f:
                print(key, np.array(f[key]).squeeze())


== \\allen\aind\scratch\ophys\Andrew\VIP_synaptic_dynamics\iGluSnFR4f+RCaMP3\836174\836174_2026-06-17_12-51-17\slap2\static_data\structure_volume_20260617_132712_DMD1.meta
acquisitionPathIdx 1.0
acquisitionPathName [ 80  97 116 104  49]
channelsSave 1.0
dmdPixelsPerColumn 800.0
dmdPixelsPerRow 1280.0
remoteFocusPosition_um -199.875
AcquisitionContainer/ScannerParameters/fovSize [ 800. 1280.]
AcquisitionContainer/ScannerParameters/pixelDilationXY [9. 5.]
AcquisitionContainer/ParsePlan/rasterOffsetXY [0 0]
AcquisitionContainer/ParsePlan/rasterSizeXY [1280  800]
#refs#/P1/dmdPixel2SampleTransform [[ 2.49078359e-01  2.91714775e-03  0.00000000e+00  0.00000000e+00]
 [-8.84719002e-04  2.50635965e-01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-1.90231658e+00 -6.34521503e-01  0.00000000e+00  1.00000000e+00]]
#refs#/Q1/dmdPixel2SampleTransform [[  0.17567303   0.16170638   0.           0.        ]
 [  0.19697303  -0.1762997    0.       

In [5]:
with tifffile.TiffFile(paths[0]) as tif:
    print(len(tif.pages))
    print(tif.pages[0].shape)
    print(tif.pages[0].dtype)
    print(tif.pages[0].description[:4000])

101
(800, 1280)
float32
{"SLAP2ReferenceStackFileVersion":2,"z":-199.875,"channel":1,"acquisitionPathIdx":1,"sourceTifFile":"F:\\slap2Data\\836174_2026-06-17_12-51-17\\ref_volume_20260617_132712_DMD1.tif","dmdPixel2SampleTransform":[[0.24907835903790651,-0.0008847190020129167,0,-1.902316580004602],[0.0029171477472943433,0.25063596511811065,0,-0.63452150251753014],[0,0,1,-199.875],[0,0,0,1]]}
